### ISSUE TITLE
Habilitado el modo de depuración

### ISSUE THREAD

**Issue by JuanjoSalvador** [python-spain/association-web#15]
Si intentas entrar en un enlace muerto en la web de Python España, nos damos de bruces con el 404 de Django en modo depuración.

![image](https://cloud.githubusercontent.com/assets/5058655/26777287/f30d8466-49dc-11e7-8d41-7581e2baa2cf.png)

**Comment by euribates** [comment]
Creo que es un fallo en el __init__.py del directorio settings, ¿no debería intentar importar de common?

**Comment by JuanjoSalvador** [comment]
Es más probable que, cómo dice la imagen, esté seteado en `True` el modo de depuración. Viene así por defecto.

Como no tengo acceso al fichero, tampoco lo puedo comprobar.

**Comment by Juanlu001** [comment]
Esta web está obsoleta. Cerrando.
