### ISSUE TITLE
No se carga el mapa

### ISSUE THREAD

**Issue by Juanlu001** [python-spain/association-web#8]
Creo que es por esto:

![screenshot from 2017-04-26 19-48-11](https://cloud.githubusercontent.com/assets/316517/25448612/543ecf6c-2ab9-11e7-8d27-14257dc20a63.png)

¿Poniendo HTTPS en los enlaces se solucionaría?

Probado en Linux con los últimos Firefox y Chromium.

**Comment by JuanjoSalvador** [comment]
A primera vista, parece un problema de CORS.

**Comment by tinproject** [comment]
En #10 he aprovechado para actualizar Leaflet y cambiar la dirección del servidor de teselas de OSM para que use HTTPS y evitar avisos de 'mixed-content'.

Me he quedado con ganas de reformatear el fichero completo.

Por otro lado JQuery solo se utiliza para la interpolación del texto del popup, Leaflet no lo necesita para nada. Se podría crear el texto del popup en JS puro y eliminar la dependencia de JQuery.

**Comment by JuanjoSalvador** [comment]
Creo que esta tarea se puede cerrar ya @juanlu001
